apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleapp
  name: sampleapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7777
  selector:
    app: sampleapp
  type: NodePort
