apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleapp
  name: sampleapp
spec:
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8092
    nodePort: 30455
  selector:
    app: sampleapp
  type: NodePort
