name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: meghakadur
        password: mpn46@71Mompavvu
    
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
