name: Build docker image and push docker image to dockerhu

on:
  push:
    branches: 
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker iamge
      run: docker build -t meghakadur/argocd:1.0.RELEASE${{ github.run_number }}  -f files/Dockerfile .


    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push meghakadur/argocd:1.0.RELEASE${{ github.run_number }} 

    - name: scanning for SBOM
      uses: anchore/sbom-action@v0
      with:
        image: meghakadur/argocd:1.0.RELEASE${{ github.run_number }} 
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v3
    - uses: advanced-security/sbom-generator-action@v0.0.1
      id: sbom
      env: 
        GITHUB_TOKEN: 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
    - uses: actions/upload-artifact@v3.1.0
      with: 
        path: ${{steps.sbom.outputs.fileName }}
        name: "SBOM"
  


         



        
        
        
        
    
  
