name: Php application to build the images
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dev/**'
      - 'argorollouts/**'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker build -t meghakadur/argocd:1.0.RELEASE-${{ github.run_number }}  -f files/Dockerfile .
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push Docker image
      run: docker push meghakadur/argocd:1.0.RELEASE-${{ github.run_number }}
    - name: scanning for SBOM
      uses: anchore/sbom-action@v0
      with:
        image: meghakadur/argocd:1.0.RELEASE-${{ github.run_number }}
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v3
    - uses: advanced-security/sbom-generator-action@v0.0.1
      id: sbom
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_TOKEN }}
    - uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{steps.sbom.outputs.fileName }}
        name: "SBOM"
  modifygit:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'megha-6/cnd-pune'
          token: ${{ secrets.NEW_TOKEN }}
      - name: modify the image
        run: |
          git config user.email meghakadur691993@gmail.com
          git config user.name megha-6
          pwd
          ls
          cd dev
          cat deployment.yaml
          pwd
          sed -i "s+meghakadur/argocd.*+meghakadur/argocd:1.0.RELEASE-$RUN_NUMBER+g" deployment.yaml
          cat deployment.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USE }}R
          GIT_PASSWORD: ${{ secrets.GIT_PSW }}
          RUN_NUMBER: ${{ github.run_number }}
