name: Build docker image and push docker image to dockerhub

on:
  push:
    branches: 
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker iamge
      run: docker build -t meghakadur/argocd:1.0.RELEASE -f files/Dockerfile .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push meghakadur/argocd:1.0.RELEASE${{ github.run_number }} 
  


         



        
        
        
        
    
  
