name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB.USERNAME }}
        password:  ${{ secrets.DOCKER_HUB.PASSWORD }}
    
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
